name: Build & Release APK

on:
  push:
    # Workflow ini hanya jalan kalau anda push TAG (contoh: v1.0, v1.1)
    tags:
      - 'v*' 

permissions:
  contents: write # Izin wajib untuk membuat Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Java 17 (Sesuai settingan project anda)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Setup Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      # Build APK (Perintah sukses anda tadi)
      - name: Build APK
        run: flutter build apk --no-tree-shake-icons --release --obfuscate --split-debug-info=build/debug_info

      # Step Baru: Upload ke GitHub Releases
      - name: Create Release & Upload APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "Update Aplikasi Terbaru (Otomatis dari GitHub Actions)"
          allowUpdates: true
